import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const { EncodingIndex } = createRequire(import.meta.url)('../indexes.ts');

// Encoding §9: canonical names, with one shared-index exception.
const singleByteNames = [
  'IBM866', 'ISO-8859-2', 'ISO-8859-3', 'ISO-8859-4', 'ISO-8859-5',
  'ISO-8859-6', 'ISO-8859-7', 'ISO-8859-8', 'ISO-8859-8-I', 'ISO-8859-10',
  'ISO-8859-13', 'ISO-8859-14', 'ISO-8859-15', 'ISO-8859-16', 'KOI8-R', 'KOI8-U',
  'macintosh', 'windows-874', 'windows-1250', 'windows-1251', 'windows-1252',
  'windows-1253', 'windows-1254', 'windows-1255', 'windows-1256', 'windows-1257',
  'windows-1258', 'x-mac-cyrillic',
];
const singleByteSources = Object.fromEntries(singleByteNames.map((name) =>
  [name, (name === 'ISO-8859-8-I' ? 'ISO-8859-8' : name).toLowerCase()]));

// Encoding §5: multibyte encodings and the indexes they share.
const multibyteSources = {
  Big5: ['big5'],
  'EUC-KR': ['euc-kr'],
  gb18030: ['gb18030', 'gb18030-ranges'],
  'EUC-JP': ['jis0208', 'jis0212'],
  'ISO-2022-JP': ['jis0208', 'iso-2022-jp-katakana'],
  Shift_JIS: ['jis0208'],
  GBK: ['gb18030'],
};

// Run manually with node --import tsx. Builds and runtime use the checked-in data.
const args = process.argv.slice(2);
assert(args.length === 0 || args.length === 1 && args[0] === '--check',
  'Usage: node --import tsx src/encoding/scripts/generate-tables.mjs [--check]');
const check = args[0] === '--check';
const target = fileURLToPath(new URL('../', import.meta.url));
const license = readFileSync(new URL('./WHATWG-LICENSE.txt', import.meta.url), 'utf8').replaceAll('\r\n', '\n');
const bsd = license.slice(license.lastIndexOf('BSD 3-Clause License')).replace(/\s*- - - -\s*$/, '');
assert(bsd.includes('Redistribution and use in source and binary forms'));
const attribution = '/*!\n' + license.split('\n')[0] + '\n\n' + bsd + '\n*/\n';
const header = [
  '// Generated by src/encoding/scripts/generate-tables.mjs. Do not edit by hand.',
  '// Source: published https://encoding.spec.whatwg.org/index-*.txt files.',
  '// WHATWG source/data attribution and BSD-3-Clause terms: src/encoding/scripts/WHATWG-LICENSE.txt.',
  '',
];
const lines = [...header, attribution,
  "import { Big5Index, EncodingIndex, GB18030Ranges, JIS0208Index } from '../indexes';",
  "import type { Encoding } from '../encodings';", '', 'export const indexes = {'];
const indexClasses = { big5: 'Big5Index', 'gb18030-ranges': 'GB18030Ranges', jis0208: 'JIS0208Index' };
const vectors = {};
const chineseVectors = {};
const japaneseKoreanVectors = {};
const names = [...new Set([...Object.values(multibyteSources).flat(), ...Object.values(singleByteSources)])];
const sources = [];
// Bound simultaneous downloads. No local checkout, HTML parsing, or cache fallback.
for (let i = 0; i < names.length; i += 4) {
  sources.push(...await Promise.all(names.slice(i, i + 4).map(download)));
}

let total = 0;
for (const [name, text] of sources) {
  const url = indexURL(name);
  const identifier = /^# Identifier: ([0-9a-f]{64})$/m.exec(text)?.[1];
  assert(identifier, url + ': missing index identifier');
  const pairs = text.split('\n').filter((line) => line.trim() && !line.startsWith('#'))
    .map((line) => line.split('\t').slice(0, 2).map(Number));
  assert(pairs.length > 0, url + ': empty index');
  const ranges = name === 'gb18030-ranges';
  let previousPointer = -1;
  let previousPoint = -1;
  for (const [pointer, point] of pairs) {
    assert(Number.isSafeInteger(pointer) && pointer > previousPointer, url + ': invalid pointer order');
    assert(Number.isInteger(point) && point > 0 && point <= 0x10ffff &&
      !(point >= 0xd800 && point <= 0xdfff), url + ': invalid scalar');
    if (ranges) assert(point > previousPoint, url + ': invalid range order');
    previousPointer = pointer;
    previousPoint = point;
  }
  let values;
  if (ranges) values = pairs.flat();
  else {
    // Single-byte handlers index 0..127, including unmapped trailing pointers.
    const length = Object.values(singleByteSources).includes(name) ? 128 : pairs.at(-1)[0] + 1;
    values = new Array(length).fill(0);
    for (const [pointer, point] of pairs) {
      assert(pointer < length, url + ': pointer outside index');
      values[pointer] = point;
    }
  }
  const width = values.some((value) => value > 0xffff) ? 4 : 2;
  const packed = pack(values).toString('base64');
  assert.deepEqual(Array.from(new EncodingIndex(packed, values.length, width).values), values, url);
  total += packed.length;
  lines.push('  // ' + url, '  // Identifier: ' + identifier);
  const segments = packed.match(/.{1,100}/g);
  lines.push('  ' + key(name) + ': new ' + (indexClasses[name] ?? 'EncodingIndex') + '(');
  segments.forEach((segment, index) => lines.push("    '" + segment + "'" + (index === segments.length - 1 ? ',' : ' +')));
  lines.push('    ' + values.length + ', ' + width + ',', '  ),');

  // Expected bytes->string digests come from the downloaded source entries,
  // independently of the runtime decoder and packed representation.
  for (const [encoding, source] of Object.entries(singleByteSources)) {
    if (source !== name) continue;
    const allBytes = Array.from({ length: 256 }, (_, byte) => byte < 128 ? byte : values[byte - 128] || 0xfffd);
    vectors[encoding] = hash(Buffer.from(String.fromCodePoint(...allBytes), 'utf16le'));
  }
  if (name === 'gb18030' || name === 'big5') {
    const big5 = name === 'big5';
    const stride = big5 ? 157 : 190;
    const special = new Map([[1133, '\u00ca\u0304'], [1135, '\u00ca\u030c'],
      [1164, '\u00ea\u0304'], [1166, '\u00ea\u030c']]);
    let text = '';
    for (let pointer = 0; pointer < 126 * stride; pointer++) {
      const point = values[pointer];
      const trailing = pointer % stride;
      // §11.1.1 has four two-scalar results. Unmapped ASCII trail bytes
      // are restored and emitted after the replacement character.
      text += big5 && special.has(pointer) ? special.get(pointer) : point
        ? String.fromCodePoint(point) : '\ufffd' + (trailing < 63 ? String.fromCharCode(trailing + 64) : '');
    }
    chineseVectors[big5 ? 'Big5' : 'gb18030'] = hash(Buffer.from(text, 'utf16le'));
  }
  if (name === 'jis0208' || name === 'jis0212') {
    const text = Array.from({ length: 94 * 94 }, (_, pointer) => String.fromCodePoint(values[pointer] || 0xfffd)).join('');
    const digest = hash(Buffer.from(text, 'utf16le'));
    japaneseKoreanVectors[name === 'jis0208' ? 'EUC-JP' : 'EUC-JP JIS0212'] = digest;
    if (name === 'jis0208') {
      japaneseKoreanVectors['ISO-2022-JP'] = digest;
      let shifted = '';
      for (let pointer = 0; pointer < 60 * 188; pointer++) {
        const point = pointer >= 8836 && pointer <= 10715 ? 0xe000 + pointer - 8836 : values[pointer];
        shifted += point ? String.fromCodePoint(point) : '\ufffd' +
          (pointer % 188 < 63 ? String.fromCharCode(pointer % 188 + 0x40) : '');
      }
      japaneseKoreanVectors.Shift_JIS = hash(Buffer.from(shifted, 'utf16le'));
    }
  }
  if (name === 'euc-kr') {
    let text = '';
    for (let pointer = 0; pointer < 126 * 190; pointer++) {
      text += values[pointer] ? String.fromCodePoint(values[pointer]) : '\ufffd' +
        (pointer % 190 < 63 ? String.fromCharCode(pointer % 190 + 0x41) : '');
    }
    japaneseKoreanVectors['EUC-KR'] = hash(Buffer.from(text, 'utf16le'));
  }
  if (name === 'iso-2022-jp-katakana') {
    japaneseKoreanVectors['ISO-2022-JP katakana'] = hash(Buffer.from(String.fromCodePoint(...values), 'utf16le'));
  }
}
lines.push('};', '', '/** Encoding Standard §9 — Index single-byte (two names share one index). */', 'export const singleByteIndexes = {');
for (const [encoding, name] of Object.entries(singleByteSources)) {
  lines.push('  ' + key(encoding) + ': indexes[' + quote(name) + '],');
}
lines.push('} satisfies Partial<Record<Encoding, EncodingIndex>>;', '', 'export type SingleByteEncoding = keyof typeof singleByteIndexes;', '');

const vectorLines = [...header, '// SHA-256 of decoding bytes 0..255, as UTF-16LE, with replacement errors.', 'export const singleByteDecodeDigests = {'];
for (const encoding of singleByteNames) vectorLines.push('  ' + key(encoding) + ": '" + vectors[encoding] + "',");
vectorLines.push('};', '');
const chineseLines = [...header,
  '// SHA-256 of all two-byte pairs in pointer order, as UTF-16LE, with replacement errors.',
  '// GB18030: 126 * 190 pairs; Big5: 126 * 157 pairs, including its four two-scalar results.',
  'export const chineseDecodeDigests = {'];
for (const [name, digest] of Object.entries(chineseVectors)) chineseLines.push('  ' + key(name) + ": '" + digest + "',");
chineseLines.push('};', '');
const japaneseKoreanLines = [...header,
  '// SHA-256 of all byte pairs in pointer order, decoded with replacement, as UTF-16LE.',
  '// JIS0208/JIS0212: 94 * 94; Shift_JIS: 60 * 188; EUC-KR: 126 * 190.',
  '// Katakana: the ISO-2022-JP encoder mappings for U+FF61..U+FF9F, decoded as UTF-16LE.',
  'export const japaneseKoreanDigests = {'];
for (const [name, digest] of Object.entries(japaneseKoreanVectors)) japaneseKoreanLines.push('  ' + key(name) + ": '" + digest + "',");
japaneseKoreanLines.push('};', '');
// All downloads and round-trip checks finish before any generated output is written.
write(resolve(target, 'gen/indexes.ts'), lines.join('\n'));
write(resolve(target, '../../test/encoding/gen/single-byte-vectors.ts'), vectorLines.join('\n'));
write(resolve(target, '../../test/encoding/gen/chinese-vectors.ts'), chineseLines.join('\n'));
write(resolve(target, '../../test/encoding/gen/japanese-korean-vectors.ts'), japaneseKoreanLines.join('\n'));
console.log('Verified ' + names.length + ' published indexes for ' + singleByteNames.length +
  ' single-byte names and multibyte codecs; ' + (total / 1024).toFixed(2) + ' KiB base64.');

function indexURL(name) { return `https://encoding.spec.whatwg.org/index-${name}.txt`; }

async function download(name) {
  const url = indexURL(name);
  const response = await fetch(url, { signal: AbortSignal.timeout(30000) });
  assert(response.ok, url + ': HTTP ' + response.status);
  return [name, (await response.text()).replaceAll('\r\n', '\n')];
}

function quote(text) { return "'" + text.replaceAll("'", "\\'") + "'"; }
function key(text) { return /^[A-Za-z_$][\w$]*$/.test(text) ? text : quote(text); }
function hash(value) { return createHash('sha256').update(value).digest('hex'); }

function write(path, text) {
  let previous;
  try { previous = readFileSync(path, 'utf8').replaceAll('\r\n', '\n'); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (check) assert(previous === text, 'Generated output differs: ' + path);
  else if (previous !== text) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
    console.log('Wrote ' + path);
  }
}

function pack(values) {
  const bytes = [];
  let previous = 0;
  function write(value) {
    while (value >= 128) { bytes.push((value & 127) | 128); value >>>= 7; }
    bytes.push(value);
  }
  const signed = (value) => value >= 0 ? value * 2 : -value * 2 - 1;
  for (let i = 0; i < values.length;) {
    const value = values[i];
    let end = i + 1;
    if (value === 0) {
      while (end < values.length && values[end] === 0) end++;
      write(0); write(end - i); i = end;
    } else {
      while (end < values.length && values[end] === value + end - i) end++;
      if (end - i >= 4) {
        write(1); write(end - i); write(signed(value - previous));
        previous = values[end - 1]; i = end;
      } else { write(signed(value - previous) + 2); previous = value; i++; }
    }
  }
  return Buffer.from(bytes);
}
