import type { FetchResponse } from '../../fetch/index';
import { obtainURLOrigin, type URLRecord } from '../../url/index';
import type { Environment } from '../scripting/environment';

/** A named destination for reports generated by one global. */
// https://w3c.github.io/reporting/#concept-endpoints
export class ReportingEndpoint {
  /** ASCII name referenced by a policy's reporting configuration. */
  name: string;
  /** Absolute destination URL, resolved against the configuring response URL. */
  url: URLRecord;
  /** Consecutive unsuccessful delivery attempts for this endpoint. */
  failures = 0;

  constructor(name: string, url: URLRecord) {
    this.name = name;
    this.url = url;
  }

  /** Read Reporting-Endpoints, ignoring invalid members and untrustworthy origins. */
  // https://w3c.github.io/reporting/#process-header
  static parse(response: FetchResponse, env: Environment): ReportingEndpoint[] {
    const { userAgent } = env;
    const baseURL = response.url;
    // Reporting still references HTTPS state, absent from the current Fetch Standard.
    // HTTPS origins already satisfy the origin trust check.
    if (baseURL === null || !userAgent.isOriginPotentiallyTrustworthy(obtainURLOrigin(baseURL))) return [];

    const dictionary = response.headerList.getStructuredFieldValue('Reporting-Endpoints', 'dictionary');
    if (dictionary === null) return [];

    const endpoints: ReportingEndpoint[] = [];
    for (const [name, member] of dictionary.members) {
      if (member.type !== 'item' || member.bareItem.type !== 'string') continue;
      const { url } = env.parseURL(member.bareItem.value, baseURL);
      if (url === null || !userAgent.isOriginPotentiallyTrustworthy(obtainURLOrigin(url))) continue;
      endpoints.push(new ReportingEndpoint(name, url));
    }
    return endpoints;
  }
}
