import { defineInterface, idlType, impl, op, roAttr, xattr } from '../../web-idl/index';
import { ReportBodyImpl } from './report';

/** Observer-visible body generated by Reporting's automation test-report operation. */
export class TestReportBodyImpl extends ReportBodyImpl {
  /** Message supplied by the automation caller. */
  #message: string;

  constructor(message: string) {
    super();
    this.#message = message;
  }

  get message(): string {
    return this.#message;
  }
}

// The draft calls the field body_message; Blink, Gecko, and WebKit expose message.
// Follow their hidden derived interface, using the same projection as policy bodies.
/*
 * [Exposed=(Window,Worker), LegacyNoInterfaceObject]
 * interface TestReportBody : ReportBody {
 *   readonly attribute DOMString message;
 *   [Default] object toJSON();
 * };
 */
export const testReportBodyIDL = defineInterface({
  name: 'TestReportBody',
  inherits: 'ReportBody',
  exposed: ['Window', 'Worker'],
  ...xattr('LegacyNoInterfaceObject'),
  implementation: impl(TestReportBodyImpl),
  members: [
    roAttr('message', idlType.DOMString),
    op('toJSON', idlType.object, [], xattr('Default')),
  ],
});
